services:
    netgen_layouts.contentful.service:
        class: Netgen\Layouts\Contentful\Service\Contentful
        arguments:
            - []
            - "@netgen_layouts.contentful.entry_slugger.configurable"
            - "@contentful.delivery.main_client"
            - "@doctrine.orm.entity_manager"
            - "@filesystem"
            - "%netgen_layouts.contentful.cache_dir%"
            - "%netgen_layouts.contentful.routing.content_types%"

    netgen_layouts.contentful.command.sync:
        class: Netgen\Bundle\LayoutsContentfulBundle\Command\SyncCommand
        arguments:
              - "@netgen_layouts.contentful.service"
              - "@filesystem"
        tags:
              - { name: console.command, command: contentful:sync }

    netgen_layouts.contentful.command.routes:
        class: Netgen\Bundle\LayoutsContentfulBundle\Command\RoutesCommand
        arguments:
              - "@netgen_layouts.contentful.service"
              - "@filesystem"
              - "@doctrine.orm.entity_manager"
        tags:
              - { name: console.command, command: contentful:routes }

    netgen_layouts.contentful.entry_slugger.configurable:
        class: Netgen\Layouts\Contentful\Routing\EntrySlugger\Configurable
        arguments:
            - "%netgen_layouts.contentful.entry_slug_type%"

    netgen_layouts.contentful.entry_slugger.simple:
        class: Netgen\Layouts\Contentful\Routing\EntrySlugger\Simple
        tags:
            - { name: netgen_layouts.contentful.entry_slugger, type: simple }

    netgen_layouts.contentful.entry_slugger.with_space:
        class: Netgen\Layouts\Contentful\Routing\EntrySlugger\WithSpace
        tags:
            - { name: netgen_layouts.contentful.entry_slugger, type: with_space }

    netgen_layouts.contentful.client_options:
        class: Contentful\Delivery\ClientOptions

    netgen_layouts.contentful.resource_pool:
        class: Contentful\Delivery\ResourcePool\Factory
        factory: ['Contentful\Delivery\ResourcePool\Factory', 'create']
        arguments:
            - "@contentful.delivery.main_client"
            - "@netgen_layouts.contentful.client_options"

    netgen_layouts.contentful.link_resolver:
        class: Contentful\Delivery\LinkResolver
        arguments:
            - "@contentful.delivery.main_client"
            - "@netgen_layouts.contentful.resource_pool"

    netgen_layouts.contentful.rich_text_parser:
        class: Contentful\RichText\Parser
        arguments:
            - "@netgen_layouts.contentful.link_resolver"
