services:
    netgen_layouts.contentful.templating.twig.extension.contentful:
        class: Netgen\Bundle\LayoutsContentfulBundle\Templating\Twig\Extension\ContentfulExtension
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: twig.extension }

    netgen_layouts.contentful.templating.twig.runtime.contentful:
        class: Netgen\Bundle\LayoutsContentfulBundle\Templating\Twig\Runtime\ContentfulRuntime
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: twig.runtime }

    netgen_layouts.contentful.templating.twig.extension.richtext:
        class: Contentful\RichText\Bridge\TwigExtension
        tags:
            - { name: twig.extension }
