view:
    item_view:
        default:
            contentful_entry:
                template: "@nglayouts/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
        ajax:
            contentful_entry:
                template: "@nglayouts/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
        app:
            contentful_entry:
                template: "@nglayouts_admin/app/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
