security:
    enable_authenticator_manager: true

    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: [ROLE_NGLAYOUTS_ADMIN]

    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: plaintext

    firewalls:
        main:
            lazy: true
            provider: users_in_memory
            http_basic: ~

    access_control:
        - { path: ^/nglayouts/(api|(dev/)?app|admin), roles: ROLE_NGLAYOUTS_ADMIN }
        - { path: ^/cb, roles: ROLE_NGLAYOUTS_ADMIN }
